// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtFJJ09UgTVmbhYvEltoT1hGzstbr-A5o',
    appId: '1:484752358530:web:1956c95e11d6d2e25dc89b',
    messagingSenderId: '484752358530',
    projectId: 'healthy-tracker-target',
    authDomain: 'healthy-tracker-target.firebaseapp.com',
    storageBucket: 'healthy-tracker-target.firebasestorage.app',
    measurementId: 'G-WREM8EHR4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPD1mBZW1lQkWAnbastovYKS8IpnBnb4A',
    appId: '1:484752358530:android:e7d77b01afd2aee45dc89b',
    messagingSenderId: '484752358530',
    projectId: 'healthy-tracker-target',
    storageBucket: 'healthy-tracker-target.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPj0LByXLr4LJ71ePONytKzjhNZ2tAlk0',
    appId: '1:484752358530:ios:fa529cbbc919ced55dc89b',
    messagingSenderId: '484752358530',
    projectId: 'healthy-tracker-target',
    storageBucket: 'healthy-tracker-target.firebasestorage.app',
    iosClientId: '484752358530-rcv2nggm1ari9rhmojl2v27i1fv0eguh.apps.googleusercontent.com',
    iosBundleId: 'com.example.bestFlutterUiTemplates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPj0LByXLr4LJ71ePONytKzjhNZ2tAlk0',
    appId: '1:484752358530:ios:fa529cbbc919ced55dc89b',
    messagingSenderId: '484752358530',
    projectId: 'healthy-tracker-target',
    storageBucket: 'healthy-tracker-target.firebasestorage.app',
    iosClientId: '484752358530-rcv2nggm1ari9rhmojl2v27i1fv0eguh.apps.googleusercontent.com',
    iosBundleId: 'com.example.bestFlutterUiTemplates',
  );
}
